#todas las configuraciones de propiedades de spring

#puerto personalizado
server:
  port:  8030
#ocultar pagina error tomcat?  
  error:
    whitelabel:
      enabled:
        false
#directorio por defecto para paginas de error
    path:
      /error

#habilitar jdbc
spring:
  data: 
    jdbc:
      repositories:
        enabled: true
  banner:
    location: classpath:static/bannerpersonalizado.txt
    
   #definir el jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/tablas_basicas?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    #pass mysqlwindows
    #pass mysqlmac
    #password: root1234
    password: root
  #configuracion jpa
  jpa:
    #mostrar querys en log
    show-sql: true
    
    #preferencias especificas hibernate
    hibernate:
      #cuando arrancas el servidor, comprueba las entitys contra las tablas, si no se corresponden
      #va a hacer "update" para actualizar las tablas, mandan las entity contra las tablas
      ddl-auto: update
      #el dialecto que va a usar al hacer las consultas
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
       
    properties:
      hibernate:
        #el dialecto que va a usar al hacer las consultas
        dialect: org.hibernate.dialect.MySQL5Dialect
     
#configuracion para thymeleaf
  thymeleaf:
    #spring detecta si la vista a sido modificada, si esto esta a true, y la vista no esta modificada la coge de cache, mejora rendimiento
    cache: true 
    #spring comprueba si la template existe antes de renderizar
    check-template: true
    #spring comprueba si el directorio del template existe antes de renderizar
    check-template-location: true
    #directorio para que spring busque las vistas
    prefix: classpath:/templates/
    #sufijo de las vistas
    suffix: .html
